### ISSUE TITLE
Make the sidebar wider

### ISSUE THREAD

**Issue by jenweber** [ember-learn/deprecation-app#1058]
The sidebar is too narrow. Modify the CSS to make it so that most deprecation names fit on one line. test your work in mobile, tablet, and desktop widths. This is probably a small change, like 

This ticket is good for new contributors.

<img width="1085" alt="Screen Shot 2022-01-06 at 11 56 01 AM" src="https://user-images.githubusercontent.com/16627268/148420191-b1e42b0a-6995-46b3-b5f9-99f6c4df81a5.png">

**Comment by harshith-venkatesh** [comment]
@jenweber  If no one has taken this task up yet, Could I go ahead with this task?

**Comment by jenweber** [comment]
Closed by #1147
