### ISSUE TITLE
`implicit-injections` deprecation is missing for v4.x series

### ISSUE THREAD

**Issue by SergeAstapov** [ember-learn/deprecation-app#1065]
DEPRECATION: As of Ember 4.0.0, owner.inject no longer injects values into resolved instances, and calling the method has been deprecated. Since this method no longer does anything, it is fully safe to remove this injection. As an alternative to this API, you can refactor to explicitly inject `_ajaxRequest` on `adapter`, or look it up directly using the `getOwner` API. [deprecation id: remove-owner-inject] See https://deprecations.emberjs.com/v4.x#toc_implicit-injections for more details.

More some background, see https://github.com/ember-fastboot/ember-cli-fastboot/issues/869

**Comment by locks** [comment]
Relevant PR has been merged!
