### ISSUE TITLE
Document `setting-on-hash` deprecation

### ISSUE THREAD

**Issue by bertdeblock** [ember-learn/deprecation-app#1085]
Motivation:
https://github.com/emberjs/ember.js/issues/19975

Location where the deprecation is triggered:
https://github.com/glimmerjs/glimmer-vm/blob/9c44e6835d27fcc7dc0e276cf3b0ee011d1ffb90/packages/%40glimmer/runtime/lib/helpers/hash.ts#L15-L21

**Comment by bertdeblock** [comment]
I'm not sure how we normally handle documentation for deprecations coming from the VM, but since people will run into this (I have as well), it seems useful to have some documentation around this?

**Comment by locks** [comment]
I think we just absorb it into Ember.

**Comment by shubham-y** [comment]
Hey @locks , I would like to work on this issue

**Comment by locks** [comment]
Assigned!
