### ISSUE TITLE
Consider having a form on the app to submit a new deprecation

### ISSUE THREAD

**Issue by locks** [ember-learn/deprecation-app#109]
I would like to lower entry barriers to the various kinds of contributing as much as possible.
In that sense, I was wondering if having a web form that someone can use to submit a deprecation would be useful. I am unsure how we would deal with the whole GitHub auth bit…

**Comment by MelSumner** [comment]
We can link to this one until we get something embedded, if you want: https://airtable.com/shr1gPvNnyiDmh3gO

**Comment by albertpak** [comment]
@MelSumner would this form just be on a homepage of deprecations app?

**Comment by MelSumner** [comment]
@albertpak it could just be a link that says "do you think we're missing a deprecation? Let us know!" and a link to the airtable form.

**Comment by locks** [comment]
Given the current bar for submitting deprecation content is a markdown file with some required frontmatter, the approached suggested here seems over-engineered, so I'm retracting my suggestion!
