### ISSUE TITLE
update html - first heading element should be an H1

### ISSUE THREAD

**Issue by MelSumner** [ember-learn/deprecation-app#11]
**Expected:** 
When the heading elements are used correctly, the styles are implemented appropriately.  

There should be 1 h1 element per page- "Deprecations" is an h2 at the moment. 
As a result, the other heading elements should be updated to ensure that the html is semantic. h1, then h2, then h3, etc., noting that there can be multiple sibling heading elements but no sibling heading elements should be skipped (i.e., h1 then h3) OR out of order (i.e. h2 then h4 then h3).

**Comment by serenaf** [comment]
WIP PR: https://github.com/ember-learn/deprecation-app/pull/104

**Comment by jaredgalanis** [comment]
Addressed in #458
