### ISSUE TITLE
Mismatched IDs causing content to not be found

### ISSUE THREAD

**Issue by MelSumner** [ember-learn/deprecation-app#117]
From @locks :

​​We have two problems. 
Example: https://deprecations-app-prod.herokuapp.com/deprecations/v3.x/#toc_use-notifypropertychange-instead-of-propertywillchange-and-propertydidchange
​​
​​The URL of the deprecation does not match what is present in the source code: https://github.com/emberjs/ember.js/commit/dabdd894423ecb148665b0f7fea0b72a1bde521d#diff-ad2e085482c0aad203f5f555a3497bcdR63
​​The id listed in the content does not match what is present in the source code: https://github.com/emberjs/ember.js/commit/dabdd894423ecb148665b0f7fea0b72a1bde521d#diff-ad2e085482c0aad203f5f555a3497bcdR61
​​
​​What this means is that when someone clicks on the link from the deprecation warning, they will go to the top of the 3.x page. Further, if they try to do a “find in page” for the deprecation id present in the source code, they will not find a match.

**Comment by kennethlarsen** [comment]
It looks to me like this is fixed. Closing for now.
