### ISSUE TITLE
Update listings on the homepage

### ISSUE THREAD

**Issue by locks** [ember-learn/deprecation-app#1170]
Currently, we list deprecations for Ember, Ember Data, and Ember CLI under the heading of a major version:

![version table, with version numbers as headers, and project names as rows](https://user-images.githubusercontent.com/32344/180647615-af7316e0-86b8-4bd3-a8ea-50c27a38b4a7.png)

We want to switch this so that the header is the project name (or logo), and the relevant versions are listed below. You can find the logos for the various projects at https://emberjs.com/logos/, if you want to use them!

**Comment by MehulKChaudhari** [comment]
Hey @locks, I would like to take this up.
