### ISSUE TITLE
Move `Ember.String` deprecation to v3

### ISSUE THREAD

**Issue by locks** [ember-learn/deprecation-app#118]
Someone—who totally isn't me,—delayed the `Ember.String` deprecation long enough that whenever it lands, it will be in the 3.x series.

We need to move the following two files from v2 to v3:
* https://github.com/ember-learn/deprecation-app/blob/master/content/ember/v2/ember-string-namespace.md
* https://github.com/ember-learn/deprecation-app/blob/master/content/ember/v2/ember-string-prototype-extensions.md

To do that you need to move the files from one folder to another, and then update the "until" to "4.0.0".

You don't need to worry about the content for now.

**Comment by GavinJoyce** [comment]
Looks like this can be closed
