### ISSUE TITLE
Add hover color and/or cursor: pointer to sidebar version numbers

### ISSUE THREAD

**Issue by arafatiqbal** [ember-learn/deprecation-app#1243]
When hovering over the sidebar, It's hard to tell that version numbers are clickable. Could we possibly add a hover color, and/ or cursor pointer to make it obvious that these items are clickable?
<img width="446" alt="image" src="https://user-images.githubusercontent.com/70502771/206976568-de62eb5d-f140-4c30-9fe7-fa600fb687d0.png">

**Comment by jenweber** [comment]
closed via https://github.com/ember-learn/deprecation-app/pull/1244

Thank you!
