### ISSUE TITLE
App seems broken

### ISSUE THREAD

**Issue by sivakumar-kailasam** [ember-learn/deprecation-app#125]
try visiting http://emberjs.com/deprecations/v2.x#toc_injected-container-access. There are a bunch of script issues & the url is being redirected to production url instead of being proxied.

//cc @serenaf @mansona

**Comment by serenaf** [comment]
@sivakumar-kailasam 👋 Long time no see my friend. I just checked this and it works fine for me. Could we maybe close this? 🤔

**Comment by sivakumar-kailasam** [comment]
👋 hey @serenaf, it's been a while 🙂

This definitely works now.
