### ISSUE TITLE
URL Scheme for deprecations

### ISSUE THREAD

**Issue by kategengler** [ember-learn/deprecation-app#1256]
We've had a handful of deprecations that were initially in ember-source 3.x but were `until 5.0` or were later changed to be until 5.0. With the new Major delivery cadence, this will likely happen more often. 

Ideally, the grouping by version on the website would get you everything you need to handle in order to move to the next major (so 4.x would have everything that is `until: 5.0`. 

I propose that each deprecation should have a URL based only on it's `id` property, so that version can be updated without the need to update URLs or potentially break old URLs.

**Comment by mansona** [comment]
Hey 👋 myself and @jenweber paired on this a bit today and it's pretty promising 🎉 

I don't want to jinx it but it looks like it might be ready to be able to release something that has a direct link to a deprecation using the format https://deprecations.emberjs.com/id/ember-polyfills-deprecate-assign maybe even as soon as next week

**Comment by jenweber** [comment]
Here's what we have so far: https://github.com/ember-learn/deprecation-app/pull/1261
