### ISSUE TITLE
Deprecation guide for Deprecate Globals Resolver RFC

### ISSUE THREAD

**Issue by Gaurav0** [ember-learn/deprecation-app#153]
Deprecate Globals Resolver RFC: https://github.com/emberjs/rfcs/pull/331

Here are some notes to help me create a deprecation guide.

* This is not a full transition guide, just an overview
* If you can, transition to ember-cli, most of the community uses it
* What is deprecated
  - Using the globals resolver (use ember-cli resolver instead)
  - Creating a global namespace (just use a directory)
  - Using Ember.TEMPLATES[] array (get template from new resolver)
  - Placing a template directly in index.html (use template precompiler that comes with your Ember version)
* To adapt your existing build tool and configuration
  - link to repo of new resolver to extend from (https://github.com/ember-cli/ember-resolver)
  - the resolver uses amdStrict module syntax rather than App.NameOfThingTypeOfThing
  - ember-cli provides a nice system for building compatible AMD modules

Edit: I will attempt to draft this myself.

**Comment by hakilebara** [comment]
This documentation guide needs to be added to the ember deprecation app: https://github.com/ember-learn/deprecation-app#adding-new-deprecations

**Comment by Gaurav0** [comment]
@hakilebara Are you saying this is the wrong repo?

**Comment by hakilebara** [comment]
😅 this is the right repo sorry my bad.  Please disregard my comment
