### ISSUE TITLE
Clarify use of private API for deprecation solution

### ISSUE THREAD

**Issue by jenweber** [ember-learn/deprecation-app#157]
defineProperty is private API, but we suggest it as a way to resolve a deprecation. We should give more guidance for alternatives:

Edward Faulkner’s comments from Slack:

it depends why they’re using it. 

 - If they’re trying to use it as a polyfill for the native `Object.defineProperty`, they should just use that directly. Every browser Ember supports has that, and Ember itself depends on it. 
 - If they’re trying to make computed properties on a plain old Javascript object, they should not do that. They should either make the object an Ember.Object and declare computed properties in the normal way, or they should keep the object as a POJO and use Object.defineProperty to make a native getter.
 - If they’re creating computed properties and can’t do it the normal way because they don’t know what the dependent keys are until after construction, they should do their own dependency observation with `addObserver` and `notifyPropertyChange`. This is an advanced thing to be doing, more likely in an addon that’s trying to present a whole new API on top of Ember than in an app.

**Comment by kennethlarsen** [comment]
@jenweber It looks like it is now marked as public instead (https://github.com/emberjs/ember.js/pull/17028) - should we close this issue?

**Comment by jenweber** [comment]
Agreed, closed. Thanks!
