### ISSUE TITLE
Missing deprecation

### ISSUE THREAD

**Issue by btecu** [ember-learn/deprecation-app#270]
Deprecation for `https://emberjs.com/deprecations/v3.x#toc_events-inherited-function-listeners` is missing:
https://github.com/emberjs/ember.js/commit/da28ceadc37c0d3f7ad4ba150defd70285233e9c#diff-bf6ea11a7c025a4430907ebb36d974dfR576

cc @pzuraq

**Comment by pzuraq** [comment]
The link appears to work currently, though it’s redirecting to a heroku URL. Could be something up with DNS?

**Comment by btecu** [comment]
It was the right file but wrong link. See updated link.

**Comment by pzuraq** [comment]
Mm, I think it’s this one: https://github.com/ember-learn/deprecation-app/blob/master/content/ember/v3/deprecate-inherit-function-listeners.md, looks like it got renamed but we forgot to rename it in the release. Should we update the title/link id here to match the link that was released?

**Comment by pzuraq** [comment]
cc @rwjblue
