### ISSUE TITLE
Deprecations for 3.8 are not correct

### ISSUE THREAD

**Issue by tavosansal** [ember-learn/deprecation-app#300]
According to this: https://github.com/emberjs/website/pull/3852
The deprecations that are currently in 3.8 should not be there except for this one: https://deprecations-app-prod.herokuapp.com/deprecations/v3.x/#toc_component-manager-string-lookup
I am trying to upgrade my app right now and I was super confused as to why deprecations were not showing up on usages.

**Comment by rwjblue** [comment]
This info is built dynamically from the front matter of each individual deprecation guide, would you mind sending in a PR to fix it?

**Comment by tavosansal** [comment]
@rwjblue I would like to help out...but not sure what you mean :( .... could you point me to the file maybe just to get me started?

**Comment by rwjblue** [comment]
@tavosansal - This file:

https://github.com/ember-learn/deprecation-app/blob/master/content/ember/v3/deprecate-string-based-component-manager-lookup.md

Those top few lines mention the version, and that field controls where they show up in the app itself.

**Comment by kennethlarsen** [comment]
Hi @tavosansal 

Would you still be interested in helping out with this? I'll gladly help you get started.
