### ISSUE TITLE
In-page anchors do not scroll correctly on a fresh load

### ISSUE THREAD

**Issue by tavosansal** [ember-learn/deprecation-app#301]
If I want to share the URL of a particular deprecation like this one: https://deprecations-app-prod.herokuapp.com/deprecations/v3.x/#toc_component-manager-string-lookup

The page does not actually scroll to that place in the page making it very hard to find.

**Comment by mansona** [comment]
hey @tavosansal thanks for the report 🎉 this will be fixed once #302 is merged 👍 There was an issue preventing our static site generation from working properly and it went unnoticed. I have added a test that will help this in the future so we are less likely to have this issue again!
