### ISSUE TITLE
Add deprecation for Component#isVisible in 3.x 

### ISSUE THREAD

**Issue by jessica-jordan** [ember-learn/deprecation-app#321]
Please add a descriptive deprecation message to the application explaining the upcoming removal of `Component#isVisible` from the API.

Please show how users can migrate away from the usage of `isVisible` in their app according to the [How we teach this](https://github.com/Parrryy/rfcs/blob/5bd04ccbdb4be7c4b3aff2e56cbdd7a49d3fb7cf/text/0000-deprecate-component-isvisible.md#how-we-teach-this) section from the original RFC with a before & after code example:

Part of https://github.com/emberjs/rfc-tracking/issues/22

**Comment by kennethlarsen** [comment]
If anyone wants to pick this up I'll happily pair with you.

**Comment by jaredgalanis** [comment]
Closed by #536
