### ISSUE TITLE
Example for `computed-property.override` is missing a `return` in the setter

### ISSUE THREAD

**Issue by gitKrystan** [ember-learn/deprecation-app#331]
I am working on fixing `computed-property.override` deprecation warnings in our app and noticed that the example in the documentation isn't quite right.

The final example in https://github.com/ember-learn/deprecation-app/blob/master/content/ember/v3/computed-property-override.md should have:
```js
set(key, value) {
  return this._fullName = value;
}
```

My understanding (per @chancancode) is that in CP setters you have to return the value otherwise the cache will remember the wrong thing.

**Comment by rwjblue** [comment]
Thank you for reporting! Mind sending in a PR to fix?

**Comment by gitKrystan** [comment]
Yeah, no problem. :)
