### ISSUE TITLE
support more than one type

### ISSUE THREAD

**Issue by serenaf** [ember-learn/deprecation-app#39]
Deprecations in Ember 1.x have also warnings, see https://www.emberjs.com/deprecations/v1.x/#toc_binding-style-attributes

**Comment by locks** [comment]
Could this be as simple as listing deprecations then warnings per version explicitly?

**Comment by locks** [comment]
I don't know what the reasoning for the warning was, but it is not something that was repeated, so I'm ok with dropping this ticket.
