### ISSUE TITLE
Port the new header/footer styles from the website

### ISSUE THREAD

**Issue by mansona** [ember-learn/deprecation-app#50]
follow the lead of the guides-app and create `{{main-header}}` and `{{main-footer}}` template *and* separate CSS files: https://github.com/ember-learn/guides-app/tree/master/app/templates/components and https://github.com/ember-learn/guides-app/tree/master/app/styles

these new components will be copy&paste synced between deprecation-app and guides-app 👍

**Comment by serenaf** [comment]
@MelSumner Hi Mel, Sorry i think i need your help/opinion here. 
Am i right in that the website is currently using the JQery dropddown plugin, see https://getbootstrap.com/docs/3.3/javascript/#dropdowns

Let's say we would like to go online with the deprecation and the guides app next week, I am not sure what the best way going forward in this is, until we have our common navigation component in place.

1) Use Ember-bootstrap which provides the same behaviour out of the box: http://www.ember-bootstrap.com/#/components/dropdown

2) Write a very basic version of this ourselves that add the respective classes on to the relevant elements. I am worried here, that I might miss all the classes that are added to mobile clients.

**Comment by mansona** [comment]
I guess the larger question here is: are we going to be using bootstrap more generally for all the design for Guides, Deprecations and the rest of the website? 

If bootstrap is the new dependency then I'm 100% ok with including ember-bootstrap at some point in the future (still debatable if it's for this first "quick and dirty" implementation). Otherwise, and potentially in the short term, we should use [Ember Basic Dropdown](http://ember-basic-dropdown.com/) and design things ourselves.

@serenaf we can pair on adding Ember Basic Dropdown this week 👍

**Comment by serenaf** [comment]
@mansona That is a great idea, will spike it out using Ember Basic Dropdown :)

**Comment by MelSumner** [comment]
@mansona looks like we'll be going more in the flexi direction, bootstrap was just what I could implement the fastest, because I've been using it for so many years.

**Comment by MelSumner** [comment]
The goal is 0 jQuery, and everything that happens with a mouse needs to also be able to happen with a keyboard.
