### ISSUE TITLE
Incorrect example in router-events.md

### ISSUE THREAD

**Issue by JoshCrozier** [ember-learn/deprecation-app#533]
While resolving some deprecation warnings, I noticed that the example in [router-events.md](https://github.com/ember-learn/deprecation-app/blob/master/content/ember/v3/router-events.md) is incorrect.

Currently the event listeners are _not_ attached to `this.router`:

```js
this.on('routeWillChange', transition => {
  // ..
});

this.on('routeDidChange', transition => {
  // ..
});
```

Should be:
```js
this.router.on('routeWillChange', transition => {
  // ..
});

this.router.on('routeDidChange', transition => {
  // ..
});
```

I have a PR incoming for this quick documentation fix.

**Comment by jaredgalanis** [comment]
@JoshCrozier thanks for looking into this. I'll be happy to review your PR when it's available.
