### ISSUE TITLE
Remove the use of ember-cli-cjs-transform

### ISSUE THREAD

**Issue by mansona** [ember-learn/deprecation-app#56]
As per this comment, we shouldn't be including anything that isn't needed: https://github.com/ember-learn/deprecation-app/pull/54#issuecomment-364923374

We are using semver-compare in the Guides App without the need for ember-cli-cjs-transform so we can remove it here too 👍

**Comment by rwjblue** [comment]
@mansona - Maybe I'm missing something here, but seems like you and I were talking about very different packages in that PR.  That PR makes use of `semver-compare` (which is authored in CJS format), whereas your comments were referring to `compare-versions` (which is authored in UMD).

See https://github.com/omichelsen/compare-versions/blob/master/index.js#L2-L11 vs https://github.com/substack/semver-compare/blob/master/index.js#L1.

**Comment by jaredgalanis** [comment]
@mansona @rwjblue, these packages seem to do very similar things (despite the different authoring formats and steps required for import). Agree that picking one makes sense. I can update the deprecations app to use compare-versions if that's what's needed.

**Comment by Gaurav0** [comment]
semver-compare is smaller and ember-cli-cjs-transform is a build time dependency only.

**Comment by jaredgalanis** [comment]
Closing this because the transform is needed for `semver-compare` and there may be some advantages to `semver-compare` vs `compare-versions`.
