### ISSUE TITLE
[Discussion] Should we always show the anchorable-toc link

### ISSUE THREAD

**Issue by mansona** [ember-learn/deprecation-app#59]
## For: 
knownasilya [2:22 PM]
hover only works for desktop, so having it always available is better

## Against: 
tbieniek [2:17 PM]
because it is often visually disturbing
seems like a common pattern to show it on hover

**Comment by jaredgalanis** [comment]
This was removed in #458, can consider bringing it back as part of the redesign down the road.

**Comment by locks** [comment]
I think this is no longer relevant.
