### ISSUE TITLE
Follow up with the Prember Static JSON issue

### ISSUE THREAD

**Issue by mansona** [ember-learn/deprecation-app#65]
This is a placeholder issue to keep track of the forked dependencies in the package.json 

I will not go into too much detail (check out the linked issues below) but the TLDR is that if you use the latest prember and the latest ember-cli this project will fail on the following command `ember build -e production`

Prember Issue: https://github.com/ef4/prember/issues/12 Fix: https://github.com/ef4/prember/pull/15
Ember-Cli PR: https://github.com/ember-cli/ember-cli/pull/7615

**Comment by kennethlarsen** [comment]
@mansona Still relevant?

**Comment by jaredgalanis** [comment]
There are no more forked dependencies in the `package.json`.
