### ISSUE TITLE
ensure all deprecation content is up-to-date

### ISSUE THREAD

**Issue by serenaf** [ember-learn/deprecation-app#69]
- [x] Ember v1, see https://www.emberjs.com/deprecations/v1.x/
- [x] Ember v2, see https://www.emberjs.com/deprecations/v2.x/
- [x] Ember v3, see https://www.emberjs.com/deprecations/v3.x/
- [x] Ember-Data v2, see https://www.emberjs.com/deprecations/ember-data/v2.x/
- [x] Ember CLI v2, see https://www.emberjs.com/deprecations/ember-cli/v2.x/

**Comment by jenweber** [comment]
I think https://github.com/emberjs/website/pull/3099 also needs to be added

**Comment by jenweber** [comment]
https://github.com/emberjs/website/pull/2995 too

**Comment by amyrlam** [comment]
Took a stab at Ember v1. Can push future edits in a cleaner commit history...just wanted to get this up there to see if this is on the right track? https://github.com/ember-learn/deprecation-app/pull/83

**Comment by amyrlam** [comment]
Made a few PR's to address v1. The only outstanding thing (I think?) on v1 is to add the missing warning section below. Will try to get to it tmrw. 

![image](https://user-images.githubusercontent.com/1372946/36465966-987ff894-168c-11e8-9932-2b63933c0b61.png)

**Comment by serenaf** [comment]
Closing this for now, lets reopen specific issues for the missing content if there is any
