### ISSUE TITLE
Fix deploy preview build failures

### ISSUE THREAD

**Issue by jaredgalanis** [ember-learn/deprecation-app#692]
- we're consistently seeing a failure on netlify deploy preview builds around `NAJAX deprecation`
- I had thought that updating to Ember Data 3.22 would fix this, but that doesn't appear to be the case
- need to investigate possible causes of this issue and potentially contact Ember Data team

**Comment by bertdeblock** [comment]
@jaredgalanis Could it be related to [this issue mentioned on Discord](https://discord.com/channels/480462759797063690/486549196837486592/768978776473206805)?
If so, I can confirm that removing the `node_modules` folder fixes it. Hope it helps.

**Comment by ijlee2** [comment]
@bertdeblock Let's check if the issue is ongoing when you open a pull request for #715 

To my recollection, after updating Ember Data to a recent version, we might have fixed this issue by clearing the cache and restarting the build in Netlify.

**Comment by jaredgalanis** [comment]
@bertdeblock @ijlee2 I investigated this a number of weeks back and it appears that the build cache is not being cleared on the build image. I don't know if blowing away node_modules will change that, but it might. 

I "fixed" this by changing which build image is being used in Netlify (from xenial --> trusty). So you should not see the errors in your PR builds. I still plan on going back and trying to clear the cache on the xenial image manually (and I'll give your suggestion a try @bertdeblock), but for now it functions okay.  

Going to leave this issue open for now until I do that.

**Comment by bertdeblock** [comment]
Yeah, we've also ran into the same issue (where I work) when running tests in CI. Clearing the cache solved it for us 👍

**Comment by jaredgalanis** [comment]
@bertdeblock you were correct, blowing away `node_modules` definitely solved the issue. Thank you!

Closed by #693 and #730
