### ISSUE TITLE
Implement 404 page

### ISSUE THREAD

**Issue by serenaf** [ember-learn/deprecation-app#70]
![screen shot 2018-02-14 at 22 38 04](https://user-images.githubusercontent.com/1288131/36231962-ede1eca2-11d7-11e8-9635-520ec1a8e7a6.png)

**Comment by mansona** [comment]
If anyone wants to pick this up they might want to check out how we do this in the guides-app https://github.com/ember-learn/guides-app/blob/master/app/templates/error.hbs 👍

**Comment by sivakumar-kailasam** [comment]
We should consider consuming the template from ember style guide app.  ie everyone gets 404 page for free when using the add-on.

**Comment by mansona** [comment]
@sivakumar-kailasam does that exist? or is your suggestion "add the 404 to the ember-styleguide and then add it to deprecation-app"?

**Comment by sivakumar-kailasam** [comment]
I'm unsure if it exists. My suggestion is to add anything that's going to be required across ember apps to go directly into style guide going forward and have consuming apps get it because they all point to styleguide's master

**Comment by amyrlam** [comment]
very rough wip: https://github.com/ember-learn/deprecation-app/compare/master...amyrlam:serena-amy/404?expand=1

followed this https://discuss.emberjs.com/t/how-to-make-a-404-router/11349 unsure what the route handler should do? 

me and @serenaf can keep working on this

**Comment by mansona** [comment]
@amyrlam thanks for taking a stab a this and sorry for not getting back to you before now 😖 

If you take a look at what is happening in the guides app https://github.com/ember-learn/guides-app/blob/master/app/templates/error.hbs we're not actually adding any route to the router to get the 404 implementation to work (i.e. I would start on removing [this line](https://github.com/ember-learn/deprecation-app/compare/master...amyrlam:serena-amy/404?expand=1#diff-f3a289058604b2b069d07bb8e2cda60cR16)) 

What we're making use of is the default/standard error substate: https://guides.emberjs.com/v3.0.0/routing/loading-and-error-substates/#toc_code-error-code-substates. We had a long discussion on the merits of both approaches in the Guides App and ultimately opted for the error substate for overall simplicity and more consistency with what we are teaching in the Guides.

Let me know if you would like any help exploring this option 👍

**Comment by amyrlam** [comment]
sorry for the delay - that makes sense, can pick this back up with serena, just took a look at this pr https://github.com/ember-learn/guides-app/pull/24/files

**Comment by rwwagner90** [comment]
@serenaf @amyrlam @mansona is anyone working on this? Happy to take a look if you would like.

**Comment by amyrlam** [comment]
@rwwagner90 Thanks - please go ahead, this is pretty stale. I haven't been in this repo in some time
