### ISSUE TITLE
Tidy up deprecation titles

### ISSUE THREAD

**Issue by locks** [ember-learn/deprecation-app#783]
Some deprecations include the word "Deprecation" or "Deprecation" in the title. This is superfluous since these are deprecation guides, so this could be tidied up.

An example:
Deprecation: https://deprecations.emberjs.com/v3.x#toc_ember-glimmer-with-syntax
Current title: Deprecate transition methods of routes and controllers 
Updated title: Transition methods of routes and controllers

**Comment by Windvis** [comment]
I can try to do it this evening if no one else volunteers before that :smile:.
