### ISSUE TITLE
write some basic acceptance tests for the deprecation-app

### ISSUE THREAD

**Issue by serenaf** [ember-learn/deprecation-app#80]
We dont have test at the moment 🙀  We can do better :) Lets add some small acceptance tests that tests the basic functionality of the app

**Comment by mansona** [comment]
to be fair, the *current* live deprecations app doesn't have any acceptance tests so I wouldn't be hard on ourselves 😂

**Comment by sivakumar-kailasam** [comment]
> We can do better :)

![](https://media.giphy.com/media/3ofT5NbBuEq6GQ65Q4/giphy.gif)

**Comment by jaredgalanis** [comment]
We have some acceptance tests now. If we want to add more specific tests in the future we can open separate issues for those.
