### ISSUE TITLE
Deployment broken

### ISSUE THREAD

**Issue by mansona** [ember-learn/deprecation-app#90]
I'm just opening this issue so that we can keep track of the new deployment issues.

https://deprecations-app-prod.herokuapp.com/deprecations/ember/v1.x/#toc_ember-reducecomputedproperty-ember-arraycomputedproperty if you go to that link now it will break with an "Internal Server Error". I'm concerned because that seems to imply that it is running fastboot but we need to make sure that it is **only** using the prember generated static output.

Also, as per https://github.com/ef4/prember#configuring-your-webserver, we need to make sure we serve _empty.html on 404

**Comment by sivakumar-kailasam** [comment]
@mansona its because of that page was accessed that you faced it. try https://ember-website-staging-pr-3192.herokuapp.com/deprecations/ember/v1.x/#toc_ember-reducecomputedproperty-ember-arraycomputedproperty. If you still face this issue, please feel free to reopen this.
