### ISSUE TITLE
Add "guides" search 

### ISSUE THREAD

**Issue by mansona** [ember-learn/deprecation-app#94]
The current live deprecations page has a search bar which gives results for the guides. Let's add the search component to have the same functionality on this new guides app

**Comment by amyrlam** [comment]
taking a stab at this

**Comment by amyrlam** [comment]
So I have the setup the same as package.json in https://github.com/ember-learn/guides-app/pull/39 (that branch runs for me locally), but I keep getting `TypeError: Cannot read property 'algoliaId' of undefined`. Not sure? 

My WIP: https://github.com/ember-learn/deprecation-app/compare/master...amyrlam:amy/search?expand=1

**Comment by acorncom** [comment]
@amyrlam if you take a look at the `guides-app`, there is a key added to the `config/environment.js` file for `ember-algolia`. If you add that, your error above should go away

**Comment by amyrlam** [comment]
thanks! i tried to match that repo including `config/environment.js` setting https://github.com/ember-learn/deprecation-app/compare/master...amyrlam:amy/search?expand=1 ... need to debug further

**Comment by mansona** [comment]
eeek I actually forgot about this issue 😖 this was technically a blocker for the release of the first version but we are where we are 😂 

Do you want to pair on this today sometime @amyrlam to get it over the wire? I have a feeling that this is a tiny bit more complicated than "just use what's in the guides app" because of the introduction of the ember-styleguide for the header bar.

Let me know 👍

**Comment by amyrlam** [comment]
moving to wip PR https://github.com/ember-learn/deprecation-app/pull/111

**Comment by mansona** [comment]
This has now been fixed with #211 🎉 and we're not showing guides results, we're actually showing deprecations results 😱
