### ISSUE TITLE
Fix code (single ``) styling

### ISSUE THREAD

**Issue by amyrlam** [ember-learn/deprecation-app#95]
Since the `id` for this title is "locked" as legacy `id: non-standard-ways-of-calling-code-ember-set-code-and-code-ember-get-code` (aka including the backticks written out as `code`), we should preserve the backticks in the `title`. Relates to: https://github.com/ember-learn/deprecation-app/pull/96.

(1) We should fix the styling of backtick code in the left hand side table of contents.

![image](https://user-images.githubusercontent.com/1372946/36582525-bda4c7f8-1826-11e8-931a-cc32b38d0c0b.png)

(2) We should fix the styling of backtick code in the title in-line.

![image](https://user-images.githubusercontent.com/1372946/36582518-b7abca22-1826-11e8-9f01-78ae00f98be1.png)

**Comment by jaredgalanis** [comment]
Will be addressed by https://github.com/ember-learn/deprecation-app/pull/793

**Comment by jaredgalanis** [comment]
Closed by #793
